version: '3'

tasks:
  default:
    cmds:
      - task: build

  all:
    cmds:
      - task: clean
      - task: fmt
      - task: build
      - task: test

  build:
    cmds:
      - soroban contract build
      - soroban contract optimize --wasm target/wasm32-unknown-unknown/release/soroban_swap_pool_contract.wasm --wasm-out target/wasm32-unknown-unknown/release/soroban_swap_pool_contract.wasm
      - ls -l target/wasm32-unknown-unknown/release/*.wasm


  test:
    deps:
      - build
    cmd: cargo test

  clean:
    cmd: cargo clean

  fmt:
    cmd: cargo fmt --all

  check:
    cmd: cargo check